### ISSUE TITLE
Feature request: include всех объектов ниже по дереву

### ISSUE THREAD

**Issue by kukuRUSik** [RabotaRu/DocHub#100]
Сейчас для включения компонентов в контекст их необходимо включать по отдельности или всем уровнем:
```yaml
contexts:
  some.context:
    location: Some/Context
    title: some context
    components:
      - some.context.A
      - some.context.*
      - some.context.*.*
```

Хотелось бы иметь возможность включить все компонентов из определенной области:
```yaml
contexts:
  some.context:
    location: Some/Context
    title: some context
    components:
      - some.context.**
```
