### ISSUE TITLE
Bug: include разноуровневой структуры компонентов

### ISSUE THREAD

**Issue by kukuRUSik** [RabotaRu/DocHub#101]
Пример бага:
```yaml
components:
  some.component:
    entity: component
    title: some component
  some.component.i1:
    entity: component
    title: some component i1
  some.component.i1.test:
    entity: component
    title: some component i1 test
  some.component.i2:
    entity: component
    title: some component i2

contexts:
  some.context:
    location: Some/Context
    title: some context
    components:
      - some.component.*.*
```
