### ISSUE TITLE
Возможность указывания ссылки в title

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#19]
Необходима возможность обработки разметки ссылки в формате plantUML. Например,
```
title: [[https://github.com/RabotaRu/DocHub {перейти в описание} DocHub]]
entity: rectangle
links:
  - id: blabla
    direction: -->
```

**Comment by formatq** [comment]
Решено:
Нужно указывать ссылку в кавычках
```
title: "[[https://github.com/RabotaRu/DocHub {перейти в описание} DocHub]]"
entity: rectangle
links:
  - id: blabla
    direction: -->
```
