### ISSUE TITLE
Некорректно срабатывает переход по ссылке на внешний ресурс

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#20]
По примеру #19 при переходе по ссылке, которая содержит в себе адрес внешнего интернета происходит переход не на внешний сайт, а на текущий. 

Например, имеется
```
title: "[[https://github.com/RabotaRu/DocHub {перейти в описание} DocHub]]"
entity: rectangle
links:
  - id: blabla
    direction: -->
```

При клике на ссылку происходит переход не на 
`https://github.com/RabotaRu/DocHub` 
а на 
`http://localhost:8080/RabotaRu/DocHub`

ветка master
