### ISSUE TITLE
Не корректная работа source для относительных путей в родительные дирректории

### ISSUE THREAD

**Issue by cu3blukekc** [RabotaRu/DocHub#201]
Есть документ с `source: ../../../README.md`. 
```
docs:
  dochub_app_arch_desc_guide:
    location: Не важно
    type: markdown
    source: ../../../README.md
```
Находится он в `/web/public/workspace/samolet/enterprise_arch/tools/dochub/`

И судя по ошибке DocHub его пытается искать по пути где описан yaml файл, без перехода в родительские директории

`Error: ENOENT: no such file or directory, stat '/web/public/workspace/samolet/enterprise_arch/tools/dochub/README.md'`

Файл физически находится по пути `/web/public/workspace/samolet/README.md`

В плагине всё ок, в новой версии с бэкендом (и возможно с фронтендом - не могу проверить).
