### ISSUE TITLE
Уметь исключать системы из контекста / Exclude systems from context

### ISSUE THREAD

**Issue by matacoder** [RabotaRu/DocHub#256]
```yaml
  arch.sample_context:
    title: Sample Context
    location: Contexts/Samples/
    extra-links: true
    uml:
      $notation: plantuml 
      $autor: Author
      $version: 0.0.3
      $moment: 18.01.2023
    components:
      - sample.business.apps.*
    exclude-links:  # систему отображаем, но ссылки на нее и из нее не рисуем
      - sample.business.apps.id
    exclude:  # полностью исключаем систему из контекста, вместе со ссылками
      - sample.business.apps.id
```
