### ISSUE TITLE
Feature Request: Задание нескольких компонентов в контекст за раз

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#26]
Добрый день.

Интересует такая возможность, что бы при описании конкретного контекста можно было указать серию компонентов через указание его родительского неймспейса.
Например, имеется 3 компонента:
```
components:
  - dochub.services: components/dochub/l2/services.yaml
  - dochub.services.service1: components/dochub/l3/service1.yaml
  - dochub.services.service2: components/dochub/l3/service2.yaml
  - dochub.services.service3: components/dochub/l3/service3.yaml
```
и в контексте указываешь вот так:
```
...
  dochub.services:
    title: сервисы
    location: dochub/services
    extra-links: true
    components:
      - dochub.services.*
...
```

Возможна ли такая фича в будущем? (ща это не прокатывает)
