### ISSUE TITLE
Перезатерание ссылок

### ISSUE THREAD

**Issue by apoddubny** [RabotaRu/DocHub#308]
Если разместить компонент в разных файлах, и в этих разных файлах добавить ссылки, то отобразится только одна ссылка.

file1:

```yaml
components:
  c1:
    title: c1
    entity: component
    links:
      - id: c2
        title: c1->c2
        direction: <--
  c2:
    title: c2
    entity: component
  c3:
    title: c3
    entity: component
contexts:
  c123:
    components:
      - c1
      - c2
      - c3
```

file2:
```yaml
components:
  c1:
    links:
      - id: c3
        title: c1->c3
        direction: <--
```

На странице контекста отобразится только одна ссылка
