### ISSUE TITLE
Некорректно работает относительная ссылка в web версии

### ISSUE THREAD

**Issue by ValentinKozlov** [RabotaRu/DocHub#311]
В плагине относительная ссылка работает, а в вебе нет:
```
  dochub.arch_desc_guide:
    location: 07. Развитие корп архитектуры/02. Инструменты/01. DocHub/01. Руководство по описанию прикладной архитектуры
    description: Руководство по описанию прикладной архитектуры ГК Самолет
    type: markdown    
    source: ../../../README.md
```

![image_2023-05-29_18-02-18](https://github.com/RabotaRu/DocHub/assets/92431485/179f70c3-b9e2-442b-a411-efef9f2f2399)
![image_2023-05-26_14-02-31](https://github.com/RabotaRu/DocHub/assets/92431485/671f3805-9f85-4cd3-b6f6-c166a450f6db)
