### ISSUE TITLE
Линии стрелок теряют свой стиль при обратном направлении

### ISSUE THREAD

**Issue by formatq** [RabotaRu/DocHub#33]
Почему то не для всех вариантов направлений происходит окрашивание линий стрелок и они остаются красными.

<img width="734" alt="image" src="https://user-images.githubusercontent.com/3082584/152290882-6d460003-7358-4c2b-be1b-695769f97339.png">

```yaml
components:
  c1:
    title: c1
    entity: rectangle
  c2:
    title: c2
    entity: rectangle
  c3:
    title: c3
    entity: rectangle
  c4:
    title: c4
    entity: rectangle
  c5:
    title: c5
    entity: rectangle
  c6:
    title: c6
    entity: rectangle
  c7:
    title: c7
    entity: rectangle
  c8:
    title: c8
    entity: rectangle
  c9:
    title: c9
    entity: rectangle
  c10:
    title: c10
    entity: rectangle
  c11:
    title: c11
    entity: rectangle
  c12:
    title: c12
    entity: rectangle
  c13:
    title: c13
    entity: rectangle
  c14:
    title: c14
    entity: rectangle
  cc:
    title: cc
    entity: rectangle
    links:
      - id: c1
        direction: ->
        title: ->
      - id: c2
        direction: -->
        title: -->
      - id: c3
        direction: --->
        title: --->
      - id: c4
        direction: -u->
        title: -u->
      - id: c5
        direction: -l->
        title: -l->
      - id: c6
        direction: <-->
        title: <-->
      - id: c12
        direction: <-l->
        title: <-l->
      - id: c13
        direction: <-d->
        title: <-d->
      - id: c14
        direction: <->
        title: <->
      - id: c7
        direction: <-
        title: <-
      - id: c8
        direction: <--
        title: <--
      - id: c9
        direction: <---
        title: <---
      - id: c10
        direction: <-u-
        title: <-u-
      - id: c11
        direction: <-l-
        title: <-l-
```

```
context:
  cc:
    title: cc
    location: cc
    extra-links: false
    uml:
      $before: >
        skinparam {
          linetype ortho
          actorStyle awesome
          nodesep 75
          ranksep 150
        }
    components:
      - cc
      - c1
      - c2
      - c3
      - c4
      - c5
      - c6
      - c7
      - c8
      - c9
      - c10
      - c11
      - c12
      - c13
      - c14
```
