### ISSUE TITLE
Не работает include в plantuml диаграммах

### ISSUE THREAD

**Issue by ContinentalGuy** [RabotaRu/DocHub#475]
**Проблема**
Не получается подключить .puml в другой .puml файл.

Для воспроизведения ошибки прикладываю содержимое файлов.

**dochub.yaml**
```yaml
docs:
  Puml.Style:
    source: styles.puml
    type: plantuml
  Puml.File:
    source: file.puml
    type: plantuml
    location: test
  Md.File:
    source: overview.md
    type: markdown
    location: test/md
```

**styles.puml**
```puml
@startuml

hide empty members

!$disabled_color = "#CFCFCF"
!$disabled_line_color = "#DDDCE0"

skinparam {
 ClassBackgroundColor WhiteSmoke
 ClassBorderColor Grey
 ArrowColor SlateGray
 GroupBackgroundColor WhiteSmoke
 GroupBorderColor Grey
 NoteBackgroundColor WhiteSmoke
 NoteBorderColor Grey
 wrapWidth 200
}
```

**file.puml**
```
@startuml
' Не отображается ни в PlantUML сервере, ни в DocHub
'!include @document/Puml.Style
'![link](@document/Collections.Overview.V1.CreateAndFillCollection.Uml)

' Отображается в PlantUML сервере, но не отображается в DocHub
'!include styles.puml

autonumber

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml
```

**overview.md**
```
# Test

![link](@document/Puml.File)
```
