### ISSUE TITLE
Не работает переопределение шаблона

### ISSUE THREAD

**Issue by villanella** [RabotaRu/DocHub#506]
Переопределение шаблона не работает ни в стандартной метамодели dochub, ни в seaf. На seaf заведен смежный баг - https://github.com/SEAFTeam/seaf-dzo-example/issues/30

Пример переопределения

```
entities:
  components:
    presentations:
      tree:
        template: templates/tree-en.puml
```
Текущее поведение: относительный путь к шаблону ищется в папке метамодели.
Ожидаемое поведение: относительный путь к шаблону ищется локально.
