### ISSUE TITLE
Live update не работает

### ISSUE THREAD

**Issue by paul-ovchinnikov** [RabotaRu/DocHub#532]
При редактировани манифеста не работает апдейт документации:
- IntelilJ плагин - приходится скрывать плагин и показывать его заново
- в режиме rich client - перезагрузка браузера не помогает. Только docker-compose down, docker-compose up --build
Явное отключение кэша в .env - никакой реакции. Отключение кеширования браузера в консоли - никакой реакции.

Перспективно. Но очень сыро.

**Comment by rpiontik** [comment]
По п.1 для принятия тикета в работу требуется информации о версии используемой IDE IntelilJ, а также версии плагина и примера на котором плагин демонстрирует проблему. 

По п.2 docker образ предлагается для демонстрации локального развертывания документации. Он не предназначен для развития кодовой базы архитектуры. Для этого используется плагин для IDE. Подробнее о развертывании можно узнать здесь - https://dochub.info/entities/docs/blank?dh-doc-id=dochub.deployment

Также, вам помогут видео-воркшопы - https://github.com/RabotaRu/dochub?tab=readme-ov-file#%D0%B2%D0%BE%D1%80%D0%BA%D1%88%D0%BE%D0%BF%D1%8B

_Перспективно. Но очень сыро._

Проесть OpenSource. Подключайтесь и сделайте инструмент лучше.

**Comment by paul-ovchinnikov** [comment]
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024

DocHub plugin: 3.14.0

Пример:
```
contexts:
  customs:
    title: Архитектура Заказов требующих Таможенного Оформления
    location: Таможенный Заказ/Общая архитектура
    components:
      - customs-order
      - customs-negotiation
components:
  customs-negotiation:
    title: Согласование ТЗ (Таможенного Заказа)
    entity: component
    aspects:
      - customs-order-negotiation
    links:
      - id: customs-order
        title: сущность ТЗ
        direction: <-->

  customs-order:
    title: Таможенный Заказ
    entity: component
aspects:
  customs-order-negotiation:
    title: "Согласование Таможенного Заказа"
    location: "Аспекты/Таможенная Очистка"
    default-context: customs-context
```
Так же:
- плагин не распознает root.yaml. Считает проект пустым. Понимает только dochub.yaml. Пробовал root.yaml с ипортами - та же проблема
- похоже не понимает .yml расширение, только полное .yaml
